<?php

namespace Yusuke\HimatanBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLikeRepository extends EntityRepository
{
    public function selectUserLike($id)
    {
        $userImg = $this->findBy(array(
            'toUser' => $id,
            'deleteFlag' => 0,
        ));
        return count($userImg);
    }

    public function setLike($like)
    {
        $em = $this->getEntityManager();
        $em->persist($like);
        $em->flush();
    }
}
