<?php

namespace Yusuke\HimatanBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPostRepository extends EntityRepository
{
    public function setPost($post)
    {
        $em = $this->getEntityManager();
        $em->persist($post);
        $em->flush();
        return $post;
    }
}
