<?php

namespace Yusuke\HimatanBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAreaRepository extends EntityRepository
{
    public function setArea($area)
    {
        $em = $this->getEntityManager();
        $em->persist($area);
        $em->flush();
    }
}
