<?php

namespace Yusuke\HimatanBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMessageRepository extends EntityRepository
{
    public function setMessage($message)
    {
        $em = $this->getEntityManager();
        $em->persist($message);
        $em->flush();
    }
}
