services:
 #Services
    image_file_component:
        class: Yusuke\HimatanBundle\Component\ImageFile
        arguments:
            - @service_container

    s3_upload_service:
        class: Yusuke\HimatanBundle\Service\S3UploadService
        arguments:
            - @aws_s3
            - %amazon_s3_bucket_name%

    file_upload_service:
        class: Yusuke\HimatanBundle\Service\FileUploadService
        arguments:
            - @doctrine
            - @image_file_component
            - @s3_upload_service
            - @service_container
